name = "GMMInference"
uuid = "bac0df68-cab7-482a-aa4b-d3925df9b168"
authors = ["Paul Schrimpf <paul.schrimpf@gmail.com>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
